baseurl: https://david-bell.netlify.app/
languageCode: en-us
theme: hugo-theme-terminal
paginate: 5
params:
  centerTheme: no
  contentTypeName: post
  fullWidthTheme: yes
  showMenuItems: 2
  themeColor: blue
languages:
  en:
    copyright: ''
    keywords: ''
    menu:
      main:
        - identifier: about
          name: About
          url: /about
        - identifier: resumé
          name: Resumé
          url: /resume
    menuMore: Show more
    params:
      logo:
        logoHomeLink: /
        logoText: David Bell - Home
    readMore: Read more
    readOtherPosts: Read other posts
    subtitle: A simple, retro theme for Hugo
    title: David Bell
