---
title: Solo Cash Cup - July 18, 2021
author: David Bell
date: '2021-07-18'
slug: []
categories:
  - Blog
tags:
  - Fortnite
  - Cash Cup
---

Fresh off the heels of his third FNCS victory, [Falcon TaySon](https://twitter.com/taysonFN?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor) won the first solo cash cup of the season in convincing fashion, confirming what the majority of the Fortnite community already knows - that TaySon is far and away the best player alive. He finished with 183 points, two victory royales, and an average placement of 16.2. 

As awesome as his performance was, I don't think that was the biggest story of the day. [FaZe Mongraal](https://twitter.com/Mongraal) placed 11th , complete with perhaps the [most impressive late-game pop off](https://twitter.com/FaZeClan/status/1416797717548896256) I've seen this year. After not qualifying for FNCS Grand Finals two seasons in a row, struggling to find a consistent trio (all while playing the game less than he ever has) Mongraal made a commitment to turn things around, get back on the grind, and strive to be the best. Well, the practice seems to be paying off. Hopefully this is just the beginning of a much deserved comeback. 

[NRG benjyfishy](https://twitter.com/benjyfishy), on the other hand, had a less than ideal tournament. He placed 2,647th with two victory royales, but with an average placement of 56.8. I don't think this is worrisome at all as he placed fifth in the [UEFA Euro cup](https://twitter.com/benjyfishy/status/1405607291257245698) last month, and solos aren't the main game mode anyway. His attention remains on qualifying for Trio FNCS and hopefully, finally, winning the Axe of Champions.
